baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Entrance Announcement'

theme = "letter"

[params]
logo = '/images/olmc-hermits-logo.jpg'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Wishlist'
url = 'https://wishlist.com/l/dzjqMJ'
weight = 30
