baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Entrance Announcement'

theme = "letter"

[params]
logo = '/images/olmc-hermits-logo.jpg'
author = 'JPH2 Tech'
description = 'We are happy to announce that J.P. Harbaugh II has been accepted to enter the Discalced Hermits of Our Lady of Mount Carmel in Fairfield, Pennsylvania.'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Wishlist'
url = 'https://wishlist.com/l/dzjqMJ'
weight = 20

[[menus.main]]
name = 'Monastery'
url = 'https://edcarm.org/foundations/'
weight = 30

